In [17]:
data0506 = [
            "../All_Data/new_data/手2022-05-06 114900-4.csv",
            "../All_Data/new_data/手2022-05-06 113600-3.csv",
            "../All_Data/new_data/手2022-05-06 115200-2.csv",
            "../All_Data/new_data/腳2022-05-06 120000-4.csv",
            "../All_Data/new_data/腳2022-05-06 120300-3.csv",
            "../All_Data/new_data/腳2022-05-06 120500-4.csv"]

data0510 = [
            "../All_Data/0510data/手2022-05-10 103600.csv",
            "../All_Data/0510data/手2022-05-10 103800.csv",
            "../All_Data/0510data/手2022-05-10 104000.csv",
            "../All_Data/0510data/腳2022-05-10 103600.csv",
            "../All_Data/0510data/腳2022-05-10 103800.csv",
            "../All_Data/0510data/腳2022-05-10 104000.csv"]

testTwoData=["手2022-05-10 104000.csv","腳2022-05-10 104000.csv"]

In [18]:
import pandas as pd
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

np.random.seed(202205456)

In [19]:
def SVM(data,data2):     
    train_data=[]
    train_data.append(np.array(pd.read_csv(data)))
    train_data.append(np.array(pd.read_csv(data2)))

    labelTemp=[]
    for i in range(len(train_data[0][:,16])):
        labelTemp.append(train_data[0][i,16]+train_data[1][i,16])

    labelSeries = np.array(labelTemp)

    dataTemp=[]
    for i in range(len(train_data[0][:,16])):
        dataTemp.append(list(train_data[0][i,1:4]) +list(train_data[0][i,7:10])+ list(train_data[1][i,1:4])+list(train_data[1][i,7:10]))
    dataSeries = np.array(dataTemp)

    print(dataSeries)
    print(labelSeries)
    x_train, x_test, y_train, y_test = train_test_split(dataSeries, labelSeries,test_size=0.15, random_state=222123123)


    svm = SVC(kernel="rbf",gamma = 0.5, probability=True)
    svm.fit(x_train,y_train)

    predict = svm.predict(x_test)
    svm_score = svm.score(x_test, y_test) 
    print(classification_report(y_test,predict))
    return svm_score

In [20]:
SVM(testTwoData[0],testTwoData[1])

[[ 0.03  0.04  0.   ... -9.24 -3.    0.16]
 [ 0.02  0.04  0.   ... -9.24 -3.    0.2 ]
 [ 0.02  0.04  0.   ... -9.24 -3.    0.16]
 ...
 [ 1.55 -1.    2.57 ... -9.2  -3.34 -0.11]
 [ 1.75 -0.75  3.06 ... -9.16 -3.3  -0.03]
 [ 1.75 -0.75  3.06 ... -9.24 -3.27  0.  ]]
['HTFT' 'HTFT' 'HTFT' ... 'HWFW' 'HWFW' 'HWFW']
              precision    recall  f1-score   support

        HTFT       0.87      0.76      0.81        34
        HTFW       1.00      0.34      0.51        35
        HWFT       0.95      0.80      0.87        45
        HWFW       0.73      0.99      0.84        95

    accuracy                           0.80       209
   macro avg       0.89      0.72      0.76       209
weighted avg       0.84      0.80      0.79       209



0.8038277511961722