In [2]:
data0506 = [
            "../All_Data/new_data/手2022-05-06 114900-4.csv",
            "../All_Data/new_data/手2022-05-06 113600-3.csv",
            "../All_Data/new_data/手2022-05-06 115200-2.csv",
            "../All_Data/new_data/腳2022-05-06 120000-4.csv",
            "../All_Data/new_data/腳2022-05-06 120300-3.csv",
            "../All_Data/new_data/腳2022-05-06 120500-4.csv"]

data0510 = [
            "../All_Data/0510data/手2022-05-10 103600.csv",
            "../All_Data/0510data/手2022-05-10 103800.csv",
            "../All_Data/0510data/手2022-05-10 104000.csv",
            "../All_Data/0510data/腳2022-05-10 103600.csv",
            "../All_Data/0510data/腳2022-05-10 103800.csv",
            "../All_Data/0510data/腳2022-05-10 104000.csv"]

testTwoData=["手2022-05-10 104000.csv","腳2022-05-10 104000.csv"]


dataCSV=[
   
"../All_Data/finish/手2022-05-31 112100.csv",
"../All_Data/finish/手2022-05-31 112600.csv",
"../All_Data/finish/手2022-05-31 113000.csv",
"../All_Data/finish/手2022-05-31 113400.csv",
"../All_Data/finish/手2022-05-31 113600.csv",
"../All_Data/finish/手2022-05-31 114800.csv",
"../All_Data/finish/手2022-05-31 115100.csv",
"../All_Data/finish/手2022-05-31 115600.csv",
"../All_Data/finish/手2022-05-31 115900.csv",




"../All_Data/finish/腳2022-05-31 112100.csv",
"../All_Data/finish/腳2022-05-31 112600.csv",
"../All_Data/finish/腳2022-05-31 113000.csv",
"../All_Data/finish/腳2022-05-31 113400.csv",

"../All_Data/finish/腳2022-05-31 113600.csv",

"../All_Data/finish/腳2022-05-31 114800.csv",

"../All_Data/finish/腳2022-05-31 115100.csv",

"../All_Data/finish/腳2022-05-31 115600.csv",

"../All_Data/finish/腳2022-05-31 115900.csv",


  
]

In [4]:
import pandas as pd
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

np.random.seed(202205456)

In [8]:
def SVM(data,data2):     
    train_data=[]
    train_data.append(np.array(pd.read_csv(data)))
    train_data.append(np.array(pd.read_csv(data2)))

    labelTemp=[]
    for i in range(len(train_data[0][:,16])):
        labelTemp.append(train_data[0][i,16]+train_data[1][i,16])

    labelSeries = np.array(labelTemp)

    dataTemp=[]
    for i in range(len(train_data[0][:,16])):
        dataTemp.append(list(train_data[0][i,1:4]) +list(train_data[0][i,7:10])+ list(train_data[1][i,1:4])+list(train_data[1][i,7:10]))
    dataSeries = np.array(dataTemp)

    print(dataSeries)
    print(labelSeries)
    x_train, x_test, y_train, y_test = train_test_split(dataSeries, labelSeries,test_size=0.15, random_state=222123123)


    svm = SVC(kernel="rbf",gamma = 0.5, probability=True)
    svm.fit(x_train,y_train)

    predict = svm.predict(x_test)
    svm_score = svm.score(x_test, y_test) 
    print(classification_report(y_test,predict))
    return svm_score

In [9]:
SVM(testTwoData[0],testTwoData[1])

[[ 0.03  0.04  0.   ... -9.24 -3.    0.16]
 [ 0.02  0.04  0.   ... -9.24 -3.    0.2 ]
 [ 0.02  0.04  0.   ... -9.24 -3.    0.16]
 ...
 [ 1.55 -1.    2.57 ... -9.2  -3.34 -0.11]
 [ 1.75 -0.75  3.06 ... -9.16 -3.3  -0.03]
 [ 1.75 -0.75  3.06 ... -9.24 -3.27  0.  ]]
['HTFT' 'HTFT' 'HTFT' ... 'HWFW' 'HWFW' 'HWFW']
              precision    recall  f1-score   support

        HTFT       0.87      0.76      0.81        34
        HTFW       1.00      0.34      0.51        35
        HWFT       0.95      0.80      0.87        45
        HWFW       0.73      0.99      0.84        95

    accuracy                           0.80       209
   macro avg       0.89      0.72      0.76       209
weighted avg       0.84      0.80      0.79       209



0.8038277511961722

In [49]:
def SVM2file(data,data2):     
    train_data=[]
    train_data.append(np.array(pd.read_csv(data)))


    labelTemp=[]
    for i in range(len(train_data[0][:,16])):
        labelTemp.append(train_data[0][i,16])

    labelSeries = np.array(labelTemp)

    dataTemp=[]
    for i in range(len(train_data[0][:,16])):
        dataTemp.append(list(train_data[0][i,1:4]) +list(train_data[0][i,7:10]))
    dataSeries = np.array(dataTemp)

    print(dataSeries)
    print(labelSeries)
    x_train, x_test, y_train, y_test = train_test_split(dataSeries, labelSeries,test_size=0.15, random_state=222123123)


    svm = SVC(kernel="rbf",gamma = 0.5, probability=True)
    svm.fit(x_train,y_train)

    test = pd.read_csv(dataCSV[0])
    test = np.array(test)
    betest=[]
    betestLabel=[]
    for i in range(len(test)):
        betest.append(list(test[i][1:4]) +list(test[i][7:10]))
        betestLabel.append(test[i][16])

    predict = svm.predict(betest)
    svm_score = svm.score(betest, betestLabel) 
    print(classification_report(betestLabel,predict))
    return svm_score

SVM2file(dataCSV[3],dataCSV[4])

[[ 1.000e-02  3.000e-02 -1.000e-02 -8.400e-01  9.870e+00  3.200e-01]
 [ 1.000e-02  3.000e-02 -1.000e-02 -8.400e-01  1.006e+01  3.600e-01]
 [ 0.000e+00  6.000e-02  2.000e-02 -8.400e-01  1.006e+01  3.600e-01]
 ...
 [-1.200e-01 -2.400e-01  5.000e-02  1.410e+00  8.450e+00  9.700e-01]
 [-1.200e-01 -2.400e-01  5.000e-02  1.610e+00  8.530e+00  1.240e+00]
 [-1.200e-01 -2.400e-01  5.000e-02  1.950e+00  8.720e+00  1.630e+00]]
['T' 'T' 'T' ... 'W' 'W' 'W']
              precision    recall  f1-score   support

           T       0.79      0.23      0.36       407
           W       0.75      0.97      0.84       937

    accuracy                           0.75      1344
   macro avg       0.77      0.60      0.60      1344
weighted avg       0.76      0.75      0.70      1344



0.7492559523809523

In [37]:
test = pd.read_csv(dataCSV[0])
test = np.array(test)
# print(data[0][0:14])
# print(data[0:])
# print(len(data))
dataTemp2=[]
for i in range(len(test)):
    dataTemp2.append(list(test[i][1:4]) +list(test[i][7:10]))

# print(dataTemp)    
